/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main */

#ifndef _Included_Main
#define _Included_Main
#ifdef __cplusplus
extern "C" {
#endif
// #undef Main_BUFFER_EVENTS_NUM
// #define Main_BUFFER_EVENTS_NUM 1024L
// #undef Main_CONSUMERS_NUM
// #define Main_CONSUMERS_NUM 2L
// #undef Main_TUPLE_SIZE
// #define Main_TUPLE_SIZE 64L
// #undef Main_TUPLE_NUM_PER_WINDOW
// #define Main_TUPLE_NUM_PER_WINDOW 60L
// #undef Main_WINDOW_NUM_PER_BATCH
// #define Main_WINDOW_NUM_PER_BATCH 1500L
/*
 * Class:     Main
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Main_init
  (JNIEnv *, jclass);

/*
 * Class:     Main
 * Method:    processAStep1
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_Main_processAStep1
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     Main
 * Method:    processAStep2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Main_processAStep2
  (JNIEnv *, jclass);

/*
 * Class:     Main
 * Method:    processBStep1
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_Main_processBStep1
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     Main
 * Method:    processBStep2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Main_processBStep2
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
